// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./basic.js')
  await import('./drive.js')
  await import('./link.js')
  await import('./to-disk.js')

  test.resume()
}
