// This file is autogenerated by the hyperschema compiler
// Schema Version: 3
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 3

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @gip/repos
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.buffer.preencode(state, m.key)
    state.end++ // flags are fixed size

    if (m.description) c.string.preencode(state, m.description)
    if (m.lastPushed) c.uint.preencode(state, m.lastPushed)
  },
  encode(state, m) {
    const flags = (m.description ? 1 : 0) | (m.lastPushed ? 2 : 0)

    c.string.encode(state, m.name)
    c.buffer.encode(state, m.key)
    c.uint8.encode(state, flags)

    if (m.description) c.string.encode(state, m.description)
    if (m.lastPushed) c.uint.encode(state, m.lastPushed)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const flags = c.uint8.decode(state)

    return {
      name: r0,
      key: r1,
      description: (flags & 1) !== 0 ? c.string.decode(state) : null,
      lastPushed: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @gip/branches.objects
const encoding1_6 = c.array(c.string)

// @gip/branches
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.commitOid)
    c.string.preencode(state, m.treeOid)
    state.end++ // flags are fixed size

    if (m.author) c.string.preencode(state, m.author)
    if (m.message) c.string.preencode(state, m.message)
    if (m.timestamp) c.uint.preencode(state, m.timestamp)
    if (m.objects) encoding1_6.preencode(state, m.objects)
  },
  encode(state, m) {
    const flags =
      (m.author ? 1 : 0) | (m.message ? 2 : 0) | (m.timestamp ? 4 : 0) | (m.objects ? 8 : 0)

    c.string.encode(state, m.name)
    c.string.encode(state, m.commitOid)
    c.string.encode(state, m.treeOid)
    c.uint8.encode(state, flags)

    if (m.author) c.string.encode(state, m.author)
    if (m.message) c.string.encode(state, m.message)
    if (m.timestamp) c.uint.encode(state, m.timestamp)
    if (m.objects) encoding1_6.encode(state, m.objects)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      name: r0,
      commitOid: r1,
      treeOid: r2,
      author: (flags & 1) !== 0 ? c.string.decode(state) : null,
      message: (flags & 2) !== 0 ? c.string.decode(state) : null,
      timestamp: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      objects: (flags & 8) !== 0 ? encoding1_6.decode(state) : null
    }
  }
}

// @gip/files
const encoding2 = {
  preencode(state, m) {
    c.string.preencode(state, m.branch)
    c.string.preencode(state, m.path)
    c.string.preencode(state, m.oid)
    c.string.preencode(state, m.mode)
    c.uint.preencode(state, m.size)
    state.end++ // flags are fixed size

    if (m.author) c.string.preencode(state, m.author)
    if (m.message) c.string.preencode(state, m.message)
    if (m.timestamp) c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    const flags = (m.author ? 1 : 0) | (m.message ? 2 : 0) | (m.timestamp ? 4 : 0)

    c.string.encode(state, m.branch)
    c.string.encode(state, m.path)
    c.string.encode(state, m.oid)
    c.string.encode(state, m.mode)
    c.uint.encode(state, m.size)
    c.uint8.encode(state, flags)

    if (m.author) c.string.encode(state, m.author)
    if (m.message) c.string.encode(state, m.message)
    if (m.timestamp) c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.uint.decode(state)
    const flags = c.uint8.decode(state)

    return {
      branch: r0,
      path: r1,
      oid: r2,
      mode: r3,
      size: r4,
      author: (flags & 1) !== 0 ? c.string.decode(state) : null,
      message: (flags & 2) !== 0 ? c.string.decode(state) : null,
      timestamp: (flags & 4) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

const encoding3_enum = {
  blob: 'blob',
  tree: 'tree',
  commit: 'commit',
  tag: 'tag'
}

// @gip/object-type enum
const encoding3 = {
  preencode(state, m) {
    state.end++ // max enum is 4 so always one byte
  },
  encode(state, m) {
    switch (m) {
      case 'blob':
        c.uint.encode(state, 1)
        break
      case 'tree':
        c.uint.encode(state, 2)
        break
      case 'commit':
        c.uint.encode(state, 3)
        break
      case 'tag':
        c.uint.encode(state, 4)
        break
      default:
        throw new Error('Unknown enum')
    }
  },
  decode(state) {
    switch (c.uint.decode(state)) {
      case 1:
        return 'blob'
      case 2:
        return 'tree'
      case 3:
        return 'commit'
      case 4:
        return 'tag'
      default:
        return null
    }
  }
}

// @gip/objects
const encoding4 = {
  preencode(state, m) {
    c.string.preencode(state, m.oid)
    encoding3.preencode(state, m.type)
    c.uint.preencode(state, m.size)
    c.buffer.preencode(state, m.data)
  },
  encode(state, m) {
    c.string.encode(state, m.oid)
    encoding3.encode(state, m.type)
    c.uint.encode(state, m.size)
    c.buffer.encode(state, m.data)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = encoding3.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.buffer.decode(state)

    return {
      oid: r0,
      type: r1,
      size: r2,
      data: r3
    }
  }
}

// @gip/head
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.branch)
  },
  encode(state, m) {
    c.string.encode(state, m.branch)
  },
  decode(state) {
    const r0 = c.string.decode(state)

    return {
      branch: r0
    }
  }
}

// @gip/tags.objects
const encoding6_7 = encoding1_6

// @gip/tags
const encoding6 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.oid)
    c.string.preencode(state, m.commitOid)
    c.string.preencode(state, m.treeOid)
    state.end++ // flags are fixed size

    if (version >= 3 && m.tagger) c.string.preencode(state, m.tagger)
    if (version >= 3 && m.message) c.string.preencode(state, m.message)
    if (version >= 3 && m.timestamp) c.uint.preencode(state, m.timestamp)
    if (version >= 3 && m.objects) encoding6_7.preencode(state, m.objects)
  },
  encode(state, m) {
    const flags =
      (version >= 3 && m.tagger ? 1 : 0) |
      (version >= 3 && m.message ? 2 : 0) |
      (version >= 3 && m.timestamp ? 4 : 0) |
      (version >= 3 && m.objects ? 8 : 0)

    c.string.encode(state, m.name)
    c.string.encode(state, m.oid)
    c.string.encode(state, m.commitOid)
    c.string.encode(state, m.treeOid)
    c.uint8.encode(state, flags)

    if (version >= 3 && m.tagger) c.string.encode(state, m.tagger)
    if (version >= 3 && m.message) c.string.encode(state, m.message)
    if (version >= 3 && m.timestamp) c.uint.encode(state, m.timestamp)
    if (version >= 3 && m.objects) encoding6_7.encode(state, m.objects)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      name: r0,
      oid: r1,
      commitOid: r2,
      treeOid: r3,
      tagger: version >= 3 && (flags & 1) !== 0 ? c.string.decode(state) : null,
      message: version >= 3 && (flags & 2) !== 0 ? c.string.decode(state) : null,
      timestamp: version >= 3 && (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      objects: version >= 3 && (flags & 8) !== 0 ? encoding6_7.decode(state) : null
    }
  }
}

// @gip/repos/hyperdb#0
const encoding7 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
    state.end++ // flags are fixed size

    if (m.description) c.string.preencode(state, m.description)
    if (m.lastPushed) c.uint.preencode(state, m.lastPushed)
  },
  encode(state, m) {
    const flags = (m.description ? 1 : 0) | (m.lastPushed ? 2 : 0)

    c.buffer.encode(state, m.key)
    c.uint8.encode(state, flags)

    if (m.description) c.string.encode(state, m.description)
    if (m.lastPushed) c.uint.encode(state, m.lastPushed)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const flags = c.uint8.decode(state)

    return {
      name: null,
      key: r1,
      description: (flags & 1) !== 0 ? c.string.decode(state) : null,
      lastPushed: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @gip/branches/hyperdb#1.objects
const encoding8_6 = encoding1_6

// @gip/branches/hyperdb#1
const encoding8 = {
  preencode(state, m) {
    c.string.preencode(state, m.commitOid)
    c.string.preencode(state, m.treeOid)
    state.end++ // flags are fixed size

    if (m.author) c.string.preencode(state, m.author)
    if (m.message) c.string.preencode(state, m.message)
    if (m.timestamp) c.uint.preencode(state, m.timestamp)
    if (m.objects) encoding8_6.preencode(state, m.objects)
  },
  encode(state, m) {
    const flags =
      (m.author ? 1 : 0) | (m.message ? 2 : 0) | (m.timestamp ? 4 : 0) | (m.objects ? 8 : 0)

    c.string.encode(state, m.commitOid)
    c.string.encode(state, m.treeOid)
    c.uint8.encode(state, flags)

    if (m.author) c.string.encode(state, m.author)
    if (m.message) c.string.encode(state, m.message)
    if (m.timestamp) c.uint.encode(state, m.timestamp)
    if (m.objects) encoding8_6.encode(state, m.objects)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      name: null,
      commitOid: r1,
      treeOid: r2,
      author: (flags & 1) !== 0 ? c.string.decode(state) : null,
      message: (flags & 2) !== 0 ? c.string.decode(state) : null,
      timestamp: (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      objects: (flags & 8) !== 0 ? encoding8_6.decode(state) : null
    }
  }
}

// @gip/files/hyperdb#2
const encoding9 = {
  preencode(state, m) {
    c.string.preencode(state, m.oid)
    c.string.preencode(state, m.mode)
    c.uint.preencode(state, m.size)
    state.end++ // flags are fixed size

    if (m.author) c.string.preencode(state, m.author)
    if (m.message) c.string.preencode(state, m.message)
    if (m.timestamp) c.uint.preencode(state, m.timestamp)
  },
  encode(state, m) {
    const flags = (m.author ? 1 : 0) | (m.message ? 2 : 0) | (m.timestamp ? 4 : 0)

    c.string.encode(state, m.oid)
    c.string.encode(state, m.mode)
    c.uint.encode(state, m.size)
    c.uint8.encode(state, flags)

    if (m.author) c.string.encode(state, m.author)
    if (m.message) c.string.encode(state, m.message)
    if (m.timestamp) c.uint.encode(state, m.timestamp)
  },
  decode(state) {
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.uint.decode(state)
    const flags = c.uint8.decode(state)

    return {
      branch: null,
      path: null,
      oid: r2,
      mode: r3,
      size: r4,
      author: (flags & 1) !== 0 ? c.string.decode(state) : null,
      message: (flags & 2) !== 0 ? c.string.decode(state) : null,
      timestamp: (flags & 4) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @gip/objects/hyperdb#3
const encoding10 = {
  preencode(state, m) {
    encoding3.preencode(state, m.type)
    c.uint.preencode(state, m.size)
    c.buffer.preencode(state, m.data)
  },
  encode(state, m) {
    encoding3.encode(state, m.type)
    c.uint.encode(state, m.size)
    c.buffer.encode(state, m.data)
  },
  decode(state) {
    const r1 = encoding3.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.buffer.decode(state)

    return {
      oid: null,
      type: r1,
      size: r2,
      data: r3
    }
  }
}

// @gip/tags/hyperdb#6.objects
const encoding11_7 = encoding1_6

// @gip/tags/hyperdb#6
const encoding11 = {
  preencode(state, m) {
    c.string.preencode(state, m.oid)
    c.string.preencode(state, m.commitOid)
    c.string.preencode(state, m.treeOid)
    state.end++ // flags are fixed size

    if (version >= 3 && m.tagger) c.string.preencode(state, m.tagger)
    if (version >= 3 && m.message) c.string.preencode(state, m.message)
    if (version >= 3 && m.timestamp) c.uint.preencode(state, m.timestamp)
    if (version >= 3 && m.objects) encoding11_7.preencode(state, m.objects)
  },
  encode(state, m) {
    const flags =
      (version >= 3 && m.tagger ? 1 : 0) |
      (version >= 3 && m.message ? 2 : 0) |
      (version >= 3 && m.timestamp ? 4 : 0) |
      (version >= 3 && m.objects ? 8 : 0)

    c.string.encode(state, m.oid)
    c.string.encode(state, m.commitOid)
    c.string.encode(state, m.treeOid)
    c.uint8.encode(state, flags)

    if (version >= 3 && m.tagger) c.string.encode(state, m.tagger)
    if (version >= 3 && m.message) c.string.encode(state, m.message)
    if (version >= 3 && m.timestamp) c.uint.encode(state, m.timestamp)
    if (version >= 3 && m.objects) encoding11_7.encode(state, m.objects)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint8.decode(state)

    return {
      name: null,
      oid: r1,
      commitOid: r2,
      treeOid: r3,
      tagger: version >= 3 && (flags & 1) !== 0 ? c.string.decode(state) : null,
      message: version >= 3 && (flags & 2) !== 0 ? c.string.decode(state) : null,
      timestamp: version >= 3 && (flags & 4) !== 0 ? c.uint.decode(state) : 0,
      objects: version >= 3 && (flags & 8) !== 0 ? encoding11_7.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    case '@gip/object-type':
      return encoding3_enum
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@gip/repos':
      return encoding0
    case '@gip/branches':
      return encoding1
    case '@gip/files':
      return encoding2
    case '@gip/object-type':
      return encoding3
    case '@gip/objects':
      return encoding4
    case '@gip/head':
      return encoding5
    case '@gip/tags':
      return encoding6
    case '@gip/repos/hyperdb#0':
      return encoding7
    case '@gip/branches/hyperdb#1':
      return encoding8
    case '@gip/files/hyperdb#2':
      return encoding9
    case '@gip/objects/hyperdb#3':
      return encoding10
    case '@gip/tags/hyperdb#6':
      return encoding11
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
